### ISSUE TITLE
Autocompletion case insensitive

### ISSUE THREAD

**Issue by dragokas** [raziEiL/SourceMod-Npp-Docs#1]
Hi,

thanks a much for such handy additions!

I have a question on improving autocomplete feature:

1.
When I type "PL" => I have a tip "PLATFORM_MAX_PATH"
but, when I typed "PLA" => this tip is disappear.

Can it be fixed?

2. 
Can you also make this feature accept "pl" (case insensitive) to show "PLATFORM_MAX_PATH" as well?

(Without using 3P plugin, of course, because for me it cause crash sometimes, and other issues like intercepting input when I don't need it.)

Thanks.

**Comment by raziEiL** [comment]
Hi. The **sourcemod.xml** file has valid syntax.  So, I just have nothing to fix here. Please, read more carefully about [Issues](https://github.com/raziEiL/SourceMod-Npp-Docs#issues). You can also follow me and [report this issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4833) too.
